# https://support.crowdin.com/developer/configuration-file/
project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
preserve_hierarchy: true

files:
  - source: "/core/resources/src/main/res/values/strings.xml"
    translation: "/core/resources/src/main/res/values-%android_code%/%original_file_name%"
    update_option: update_as_unapproved
    # https://developer.crowdin.com/language-codes/
    languages_mapping:
      android_code:
        zh-CN: "zh"
        es-ES: "es"
        pt-PT: "pt"

  - source: "/core/resources/src/main/res/values/languages.xml"
    translation: "/core/resources/src/main/res/values-%android_code%/%original_file_name%"
    update_option: update_as_unapproved
    languages_mapping:
      android_code:
        zh-CN: "zh"
        es-ES: "es"
        pt-PT: "pt"

  # AndroidNext
  - source: "/eggs/AndroidNext/src/main/res/values/strings.xml"
    translation: "/eggs/AndroidNext/src/main/res/values-%android_code%/%original_file_name%"
    update_option: update_as_unapproved
    languages_mapping:
      android_code:
        zh-CN: "zh"
        es-ES: "es"
        pt-PT: "pt"

  # RocketLauncher
  - source: "/eggs/RocketLauncher/src/main/res/values/strings.xml"
    translation: "/eggs/RocketLauncher/src/main/res/values-%android_code%/%original_file_name%"
    update_option: update_as_unapproved
    languages_mapping:
      android_code:
        zh-CN: "zh"
        es-ES: "es"
        pt-PT: "pt"
