name: Crowdin Synchronize

on:
  push:
    paths:
      - 'app/src/main/res/values*/strings.xml'
      - 'app/src/main/res/values*/languages.xml'
      - 'core/resources/src/main/res/values*/strings*.xml'
      - 'eggs/AndroidNext/src/main/res/values*/strings*.xml'
      - 'eggs/RockedLauncher/src/main/res/values*/strings*.xml'
      - 'crowdin.yml'
    branches: [ main ]
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Check secrets
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        if: ${{ env.CROWDIN_PROJECT_ID == '' || env.CROWDIN_PERSONAL_TOKEN == '' }}
        run: exit 0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin push
        uses: crowdin/github-action@v2 # https://github.com/marketplace/actions/crowdin-action
        with:
          upload_sources: true
          upload_translations: true
          download_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Update Crowdin progress
        run: |
          cd script/crowdin
          pip install -r requirements.txt
          python start.py ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Crowdin pull
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
